name: LS_prof
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.7=py311hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numpy=1.26.2=py311h08b1b3b_0
  - numpy-base=1.26.2=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3.1=py311h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - pytorch=2.1.2=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.1.2=py311_cu118
  - torchtriton=2.1.0=py311
  - torchvision=0.16.2=py311_cu118
  - urllib3=1.26.18=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.25.0
      - aiofiles==23.2.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - altair==5.2.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - attrs==23.1.0
      - blis==0.7.11
      - catalogue==2.0.10
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - contourpy==1.2.0
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.16.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - en-core-web-sm==3.7.1
      - fastapi==0.105.0
      - ffmpy==0.3.1
      - flash-attn==2.3.6
      - fonttools==4.46.0
      - frozenlist==1.4.0
      - fschat==0.2.34
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - gradio==3.50.2
      - gradio-client==0.6.1
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.25.2
      - huggingface-hub==0.19.4
      - importlib-resources==6.1.1
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - markdown-it-py==3.0.0
      - markdown2==2.4.11
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - nh3==0.2.15
      - ninja==1.11.1.1
      - orjson==3.9.10
      - packaging==23.2
      - pandas==2.1.4
      - peft==0.7.1
      - preshed==3.0.9
      - prompt-toolkit==3.0.43
      - protobuf==4.25.1
      - psutil==5.9.6
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pydantic==1.10.13
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-multipart==0.0.6
      - pytz==2023.3.post1
      - referencing==0.32.0
      - regex==2023.10.3
      - rich==13.7.0
      - rpds-py==0.13.2
      - safetensors==0.4.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - shortuuid==1.0.11
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - starlette==0.27.0
      - svgwrite==1.4.3
      - thinc==8.2.2
      - tiktoken==0.5.2
      - tokenizers==0.15.0
      - toolz==0.12.0
      - tqdm==4.66.1
      - transformers==4.36.1
      - typer==0.9.0
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - uvicorn==0.24.0.post1
      - wandb==0.16.1
      - wasabi==1.1.2
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.12
      - weasel==0.3.4
      - websockets==11.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
